const TempCouponData = [
  {
    id: 1,
    company: "Starbucks",
    details: "Get a free drink with any purchase!",
    offer: "Free Drink",
    expiryDate: "31 Dec 2023",
    terms: "T&C Apply",
    logo: require("../../assets/images/templogos/starbucks.png"),
    tokensRequired: "30",
  },
  {
    id: 2,
    company: "Amazon",
    details: "10% off on electronics!",
    offer: "10% Off",
    expiryDate: "15 Jan 2024",
    terms: "T&C Apply",
    logo: require("../../assets/images/templogos/amazon.png"),
    tokensRequired: "20",
  },
  {
    id: 3,
    company: "Nike",
    details: "Buy one get one free on selected shoes!",
    offer: "BOGO",
    expiryDate: "20 Feb 2024",
    terms: "T&C Apply",
    logo: require("../../assets/images/templogos/nike.png"),
    tokensRequired: "100",
  },
  {
    id: 4,
    company: "McDonald's",
    details: "Free fries with any large meal!",
    offer: "Free Fries",
    expiryDate: "10 Mar 2024",
    terms: "T&C Apply",
    logo: require("../../assets/images/templogos/mcdonalds.png"),
    tokensRequired: "18",
  },
  {
    id: 5,
    company: "Apple",
    details: "5% off on the new iPhone!",
    offer: "5% Off",
    expiryDate: "30 Apr 2024",
    terms: "T&C Apply",
    logo: require("../../assets/images/templogos/apple.png"),
    tokensRequired: "15",
  },
];

export default TempCouponData;
